## XGB

In [1]:
import os
import pandas as pd
from xgboost import XGBClassifier
import joblib
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Configuration
TRAIN_PATH = '../data/train-test/train_set.csv'
TEST_PATH = '../data/train-test/test_set.csv'
TARGET_COLUMN = 'has_diabetes'
MODEL_OUTPUT_DIR = '../models/'
MODEL_SAVE_PATH = os.path.join(MODEL_OUTPUT_DIR, 'xgboost_model.joblib')
RANDOM_SEED = 42

# Ensure model output directory exists
os.makedirs(MODEL_OUTPUT_DIR, exist_ok=True)

# Load train and test datasets
train_df = pd.read_csv(TRAIN_PATH)
test_df = pd.read_csv(TEST_PATH)

# Prepare features and target
X_train = train_df.drop(TARGET_COLUMN, axis=1)
y_train = train_df[TARGET_COLUMN]
X_test = test_df.drop(TARGET_COLUMN, axis=1)
y_test = test_df[TARGET_COLUMN]


# Initialize and train XGBoost classifier
model = XGBClassifier(
    random_state=RANDOM_SEED,
    eval_metric='logloss',
    enable_categorical=True,  # Now safe to enable
    tree_method='hist'        # Required for categorical support in XGBoost >= 1.6
)

model.fit(X_train, y_train)

# Make predictions on test set
y_pred = model.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
print(f"Test Accuracy: {accuracy:.4f}")
print("\nClassification Report:")
print(classification_report(y_test, y_pred))
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

# Save the trained model
joblib.dump(model, MODEL_SAVE_PATH)
print(f"\nModel saved to: {MODEL_SAVE_PATH}")

Test Accuracy: 0.7556

Classification Report:
              precision    recall  f1-score   support

         0.0       0.78      0.72      0.75     36413
         1.0       0.74      0.79      0.76     36412

    accuracy                           0.76     72825
   macro avg       0.76      0.76      0.76     72825
weighted avg       0.76      0.76      0.76     72825


Confusion Matrix:
[[26089 10324]
 [ 7472 28940]]

Model saved to: ../models/xgboost_model.joblib


## LightGBM

In [2]:
import os
import pandas as pd
from lightgbm import LGBMClassifier
import joblib
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Configuration
TRAIN_PATH = '../data/train-test/train_set.csv'
TEST_PATH = '../data/train-test/test_set.csv'
TARGET_COLUMN = 'has_diabetes'
MODEL_OUTPUT_DIR = '../models/'
MODEL_SAVE_PATH = os.path.join(MODEL_OUTPUT_DIR, 'lightgbm_model.joblib')
RANDOM_SEED = 42

# Ensure model output directory exists
os.makedirs(MODEL_OUTPUT_DIR, exist_ok=True)

# Load train and test datasets
train_df = pd.read_csv(TRAIN_PATH)
test_df = pd.read_csv(TEST_PATH)

# Prepare features and target
X_train = train_df.drop(TARGET_COLUMN, axis=1)
y_train = train_df[TARGET_COLUMN]
X_test = test_df.drop(TARGET_COLUMN, axis=1)
y_test = test_df[TARGET_COLUMN]


# Initialize and train LightGBM classifier
model = LGBMClassifier(
    random_state=RANDOM_SEED,
    verbose=-1,
    objective='binary',
    
)

model.fit(
    X_train, y_train
)

# Make predictions
y_pred = model.predict(X_test)

# Evaluate
accuracy = accuracy_score(y_test, y_pred)
print(f"Test Accuracy: {accuracy:.4f}")
print("\nClassification Report:")
print(classification_report(y_test, y_pred, zero_division=0))
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

# Save model
joblib.dump(model, MODEL_SAVE_PATH)
print(f"\nModel saved to: {MODEL_SAVE_PATH}")

Test Accuracy: 0.7566

Classification Report:
              precision    recall  f1-score   support

         0.0       0.78      0.72      0.75     36413
         1.0       0.74      0.80      0.77     36412

    accuracy                           0.76     72825
   macro avg       0.76      0.76      0.76     72825
weighted avg       0.76      0.76      0.76     72825


Confusion Matrix:
[[26097 10316]
 [ 7413 28999]]

Model saved to: ../models/lightgbm_model.joblib


## CatBoost

In [3]:
import os
import pandas as pd
from catboost import CatBoostClassifier
import joblib
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import numpy as np

# Configuration
TRAIN_PATH = '../data/train-test/train_set.csv'
TEST_PATH = '../data/train-test/test_set.csv'
TARGET_COLUMN = 'has_diabetes'
MODEL_OUTPUT_DIR = '../models/'
MODEL_SAVE_PATH = os.path.join(MODEL_OUTPUT_DIR, 'catboost_model.joblib')
RANDOM_SEED = 42

# Ensure model output directory exists
os.makedirs(MODEL_OUTPUT_DIR, exist_ok=True)

# Load train and test datasets
train_df = pd.read_csv(TRAIN_PATH)
test_df = pd.read_csv(TEST_PATH)

# Prepare features and target
X_train = train_df.drop(TARGET_COLUMN, axis=1)
y_train = train_df[TARGET_COLUMN]
X_test = test_df.drop(TARGET_COLUMN, axis=1)
y_test = test_df[TARGET_COLUMN]



# Initialize and train CatBoost classifier
model = CatBoostClassifier(
    random_seed=RANDOM_SEED,
    verbose=False,
    loss_function='Logloss',
    eval_metric='AUC'  
)

model.fit(
    X_train, y_train
)

# Make predictions
y_pred = model.predict(X_test)

# Evaluate
accuracy = accuracy_score(y_test, y_pred)
print(f"Test Accuracy: {accuracy:.4f}")
print("\nClassification Report:")
print(classification_report(y_test, y_pred, zero_division=0))
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

# Save model
joblib.dump(model, MODEL_SAVE_PATH)
print(f"\nModel saved to: {MODEL_SAVE_PATH}")

Test Accuracy: 0.7567

Classification Report:
              precision    recall  f1-score   support

         0.0       0.78      0.72      0.75     36413
         1.0       0.74      0.80      0.77     36412

    accuracy                           0.76     72825
   macro avg       0.76      0.76      0.76     72825
weighted avg       0.76      0.76      0.76     72825


Confusion Matrix:
[[26045 10368]
 [ 7349 29063]]

Model saved to: ../models/catboost_model.joblib


## Random Forest

In [4]:
import os
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import joblib

# Configuration
TRAIN_PATH = '../data/train-test/train_set.csv'
TEST_PATH = '../data/train-test/test_set.csv'
TARGET_COLUMN = 'has_diabetes'
MODEL_OUTPUT_DIR = '../models/'
MODEL_SAVE_PATH = os.path.join(MODEL_OUTPUT_DIR, 'random_forest_model.joblib')
RANDOM_SEED = 42

# Ensure model output directory exists
os.makedirs(MODEL_OUTPUT_DIR, exist_ok=True)

# Load train and test datasets
train_df = pd.read_csv(TRAIN_PATH)
test_df = pd.read_csv(TEST_PATH)

# Prepare features and target
X_train = train_df.drop(columns=TARGET_COLUMN)
y_train = train_df[TARGET_COLUMN]
X_test = test_df.drop(columns=TARGET_COLUMN)
y_test = test_df[TARGET_COLUMN]


# Initialize and train Random Forest classifier
model = RandomForestClassifier(
    random_state=RANDOM_SEED,
    n_estimators=100,
    n_jobs=-1  # Use all CPU cores
)
model.fit(X_train, y_train)

# Make predictions
y_pred = model.predict(X_test)

# Evaluate
accuracy = accuracy_score(y_test, y_pred)
print(f"Test Accuracy: {accuracy:.4f}")
print("\nClassification Report:")
print(classification_report(y_test, y_pred, zero_division=0))
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

# Save model
joblib.dump(model, MODEL_SAVE_PATH)
print(f"\nModel saved to: {MODEL_SAVE_PATH}")

Test Accuracy: 0.7371

Classification Report:
              precision    recall  f1-score   support

         0.0       0.75      0.72      0.73     36413
         1.0       0.73      0.76      0.74     36412

    accuracy                           0.74     72825
   macro avg       0.74      0.74      0.74     72825
weighted avg       0.74      0.74      0.74     72825


Confusion Matrix:
[[26126 10287]
 [ 8862 27550]]

Model saved to: ../models/random_forest_model.joblib


## Logistic regression

In [5]:
import os
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.preprocessing import StandardScaler
import joblib

# Configuration
TRAIN_PATH = '../data/train-test/train_set.csv'
TEST_PATH = '../data/train-test/test_set.csv'
TARGET_COLUMN = 'has_diabetes'
MODEL_OUTPUT_DIR = '../models/'
MODEL_SAVE_PATH = os.path.join(MODEL_OUTPUT_DIR, 'logistic_regression_model.joblib')
RANDOM_SEED = 42

# Ensure model output directory exists
os.makedirs(MODEL_OUTPUT_DIR, exist_ok=True)

# Load data
train_df = pd.read_csv(TRAIN_PATH)
test_df = pd.read_csv(TEST_PATH)

# Prepare features and target
X_train = train_df.drop(columns=TARGET_COLUMN)
y_train = train_df[TARGET_COLUMN]
X_test = test_df.drop(columns=TARGET_COLUMN)
y_test = test_df[TARGET_COLUMN]

scaler = StandardScaler()
X_train_scaled = pd.DataFrame(
    scaler.fit_transform(X_train),
    columns=X_train.columns,
    index=X_train.index
)
X_test_scaled = pd.DataFrame(
    scaler.transform(X_test),
    columns=X_test.columns,
    index=X_test.index
)

# Initialize and train Logistic Regression
model = LogisticRegression(
    random_state=RANDOM_SEED,
    max_iter=2000,
    solver='lbfgs'
)
model.fit(X_train_scaled, y_train)

# Predict
y_pred = model.predict(X_test_scaled)

# Evaluate
accuracy = accuracy_score(y_test, y_pred)
print(f"Test Accuracy: {accuracy:.4f}")
print("\nClassification Report:")
print(classification_report(y_test, y_pred, zero_division=0))
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

# Save artifacts
joblib.dump(model, MODEL_SAVE_PATH)
joblib.dump(scaler, os.path.join(MODEL_OUTPUT_DIR, 'standard_scaler_logistic.joblib'))

print(f"\nModel saved to: {MODEL_SAVE_PATH}")
print(f"Scaler saved to: {os.path.join(MODEL_OUTPUT_DIR, 'standard_scaler_logistic.joblib')}")

Test Accuracy: 0.7498

Classification Report:
              precision    recall  f1-score   support

         0.0       0.76      0.73      0.75     36413
         1.0       0.74      0.77      0.75     36412

    accuracy                           0.75     72825
   macro avg       0.75      0.75      0.75     72825
weighted avg       0.75      0.75      0.75     72825


Confusion Matrix:
[[26620  9793]
 [ 8427 27985]]

Model saved to: ../models/logistic_regression_model.joblib
Scaler saved to: ../models/standard_scaler_logistic.joblib


## Simple Neural Network (MLP)

In [6]:
import os
import pandas as pd
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.preprocessing import StandardScaler
import joblib

# Configuration
TRAIN_PATH = '../data/train-test/train_set.csv'
TEST_PATH = '../data/train-test/test_set.csv'
TARGET_COLUMN = 'has_diabetes'
MODEL_OUTPUT_DIR = '../models/'
MODEL_SAVE_PATH = os.path.join(MODEL_OUTPUT_DIR, 'mlp_model.joblib')
RANDOM_SEED = 42

# Ensure model output directory exists
os.makedirs(MODEL_OUTPUT_DIR, exist_ok=True)

# Load data
train_df = pd.read_csv(TRAIN_PATH)
test_df = pd.read_csv(TEST_PATH)

# Prepare features and target
X_train = train_df.drop(columns=TARGET_COLUMN)
y_train = train_df[TARGET_COLUMN]
X_test = test_df.drop(columns=TARGET_COLUMN)
y_test = test_df[TARGET_COLUMN]


scaler = StandardScaler()
X_train_scaled = pd.DataFrame(
    scaler.fit_transform(X_train),
    columns=X_train.columns,
    index=X_train.index
)
X_test_scaled = pd.DataFrame(
    scaler.transform(X_test),
    columns=X_test.columns,
    index=X_test.index
)

# Initialize and train MLP classifier
model = MLPClassifier(
    random_state=RANDOM_SEED,
    hidden_layer_sizes=(100,),          # Try (128, 64) for deeper networks if needed
    max_iter=500,
    activation='relu',
    solver='adam',
    alpha=1e-4,                         # L2 regularization
    learning_rate_init=0.001,
    early_stopping=True,                # Prevents overfitting
    n_iter_no_change=10,
    validation_fraction=0.1             # Required when early_stopping=True
)
model.fit(X_train_scaled, y_train)

# Predict
y_pred = model.predict(X_test_scaled)

# Evaluate
accuracy = accuracy_score(y_test, y_pred)
print(f"Test Accuracy: {accuracy:.4f}")
print("\nClassification Report:")
print(classification_report(y_test, y_pred, zero_division=0))
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

# Save model and scaler
joblib.dump(model, MODEL_SAVE_PATH)
joblib.dump(scaler, os.path.join(MODEL_OUTPUT_DIR, 'standard_scaler_mlp.joblib'))

print(f"\nModel saved to: {MODEL_SAVE_PATH}")
print(f"Scaler saved to: {os.path.join(MODEL_OUTPUT_DIR, 'standard_scaler_mlp.joblib')}")

Test Accuracy: 0.7561

Classification Report:
              precision    recall  f1-score   support

         0.0       0.78      0.71      0.74     36413
         1.0       0.73      0.80      0.77     36412

    accuracy                           0.76     72825
   macro avg       0.76      0.76      0.76     72825
weighted avg       0.76      0.76      0.76     72825


Confusion Matrix:
[[25812 10601]
 [ 7162 29250]]

Model saved to: ../models/mlp_model.joblib
Scaler saved to: ../models/standard_scaler_mlp.joblib


## Total Time = 34.7S